### ISSUE TITLE
Rights and License

### ISSUE THREAD

**Issue by vantuyls** [osulp/sa-content#32]
The Hyrax has metadata fields for BOTH Rights Statement and License. For content being migrated, we'd like to propose the following rules:

License:
- if a license has not been explicitly chosen in DSpace, the item will be assigned All Rights Reserved
- if a license has been chosen in DSpace, that license will be used

Rights:
- NO items in DSpace have a rights statement explicitly selected
- All ETDs will be given "In Copyright" from http://rightsstatements.org/page/1.0/?language=en
- All other items will be given "Copyright Not Evaluated" from http://rightsstatements.org/page/1.0/?language=en 

Other License note: we will start offering CC 4.0 Licenses in Hyrax

@mwillihooper thoughts on this as a starting point? I'm particularly concerned about what other items might need to have copyright assigned in the rights statement.

**Comment by vantuyls** [comment]
@mwillihooper i know we discussed some of this before, but at the time Hyrax only had one field that was conflating License and Rights. They are split up now which seems better, but means we need to make more choices.

**Comment by mwillihooper** [comment]
- Fine with the license stuff--that makes sense.

- Is the Rights field going to be visible to users? We can _technically_ apply "In Copyright" with a Creative Commons license (since CC sits on top of rather than replaces copyright)--looks like this would be the case for many ETDs. BUT it will definitely confuse some users. I can also see some confusion if there are items that have "Copyright Not Evaluated" rights statement along with a CC license or "All Rights Reserved." Can we make the license more prominent than the rights statement? Or could we not even show the rights in the default view when there is a license? For the stuff that's being migrated, any available license is going to give users more granular/accurate re-use info than the rights statement.

**Comment by mwillihooper** [comment]
@vantuyls some initial thoughts/questions above. This makes things a bit more thorny from the perspective of a user who maybe doesn't understand why there would be a rights statement and a license (most people), and which takes priority.

**Comment by vantuyls** [comment]
yeah, this is a little tricky. We can place License above Rights Statement in the form if that would help. Not sure about making Rights Statement less visible.

@mwillihooper can you think of any other content (apart from ETDs) where we have a blanket rights statement we can apply?

**Comment by vantuyls** [comment]
@mwillihooper would you prefer we assign "all rights reserved" as a license or just leave license blank when no license has been selected?

**Comment by mwillihooper** [comment]
@vantuyls: I think all collections should have "copyright not evaluated" as the rights statement except for the ETDs (and I agree we can apply "In copyright" there because nothing should be in public domain). Might want to check with @boockm since he has more history on the acquisition of the current collections.

I think "all rights reserved" would be the better license choice if we think our historic processes "caught" most uploads that were in public domain or had a CC licenses and attached the appropriate license. But if a substantial number of potentially open materials didn't have licenses attached (specifically OA articles), I'm more comfortable leaving the license blank and relying on our "copyright not evaluated" rights statement instead.

**Comment by mwillihooper** [comment]
@zhang4952 @revgum : Would there be a way to identify all works in SA that have a publication date of 1923 or before? That may allow us to label more thing as specifically public domain, which would be more granular than "copyright not evaluated."

**Comment by mwillihooper** [comment]
I just looked and we have many ETDs published before 1923, so those would be in the public domain.  Since the main purpose of rights statements is to identify works in copyright, public domain, or undetermined, I don't see a way to parse apart PD/(c) at the collection level. The main reason for something being PD is that it is authored by a federal employee in the course of their work, fell out of copyright, or was dedicated to the PD. I'm seeing a mix of PD/(c) materials in all of our collections. _So, except for items explicitly labeled as (c) or PD now, I think we will have to apply "copyright not evaluated" to everything if we're going to apply at the collection level._

Anything created before 1897 or published before 1923 would be in the public domain, though. So if we have the technical capacity to batch identify and label those documents, that is one place we can be more specific.

**Comment by vantuyls** [comment]
So:

If published before 1923 --> public domain
If published after 1923 and copyright is stated --> in copyright
If published after 1923 and copyright not stated --> copyright not evaluated

right?

**Comment by mwillihooper** [comment]
Yes, I think that is the rough sorting we're capable of. 

If something was published without certain formalities (copyright notice, registration) it is technically in the public domain up to 1978/1989 (nice chart with details [here](http://copyright.cornell.edu/resources/publicdomain.cfm)). However, I don't know of a way for the system to identify materials with/without a copyright notice. I am assuming that would just be on the scan and not consistently entered into the metadata. If there is a way to parse that, we can liberate many more works!

**Comment by mwillihooper** [comment]
Tabular summary: https://docs.google.com/spreadsheets/d/1_Mj90z_abGrmn_xz-fnM8mF_NWGDv9br7kNIs6FfQWw/edit?usp=sharing
